[package]
name = "rp"
version = "0.1.0"
edition = "2021"

[dependencies]
anstyle = "1.0"
anyhow = "1"
clap = { version = "4.1", features = ["cargo", "derive", "deprecated", "wrap_help", "unstable-styles"] }
memchr = "2.5"
regex = "1.7"
tempfile = "3.4"
thiserror = "1"
